# Generated by Django 4.2.8 on 2023-12-04 12:03

import datetime
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('BF', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner'), ('S', 'Shopping')], default=django.utils.timezone.now, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 12, 4))]),
        ),
    ]
